version: "3"

services:
  nginx:
    image: tomasfn87/nginx-test:latest
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./style.css:/usr/share/nginx/html/style.css
    
  # mysql:
  #   image: mysql:5.7
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=test
  #   volumes:
  #     - ./data:/var/lib/mysql
  
  mongodb:
    image: mongo:latest
    volumes:
    - ./db-data:/var/lib/mongodb
    - ./mongo-config:/var/lib/mongodb/config
